-- ============================================
-- Supabase Veritabanı Kurulumu
-- Influencer Başvuru Formu için Tablo ve RLS Politikaları
-- ============================================
-- 
-- Bu dosyayı Supabase Dashboard > SQL Editor'de çalıştırın
-- Adım adım çalıştırabilir veya tümünü birden çalıştırabilirsiniz
-- ============================================

-- 1. TABLO OLUŞTURMA
-- influencer_applications tablosunu oluşturur
CREATE TABLE IF NOT EXISTS public.influencer_applications (
    -- Otomatik olarak artan ve birincil anahtar (Primary Key)
    id bigint generated by default as identity NOT NULL,
    
    -- Başvuru zaman damgası (Supabase otomatik olarak ekleyebilir)
    created_at timestamp with time zone default now() NOT NULL,
    
    -- 1. Kişisel Bilgiler (Zorunlu Alanlar)
    full_name text NOT NULL,
    email text NOT NULL,
    phone_number text NOT NULL,
    gender text, -- Cinsiyet: 'Erkek', 'Kadın'
    country text NOT NULL,
    city text NOT NULL,
    
    -- İlgi Alanları (Text olarak tutulur)
    interests text,
    
    -- 2. Sosyal Medya Hesapları (Opsiyonel - En az bir tane zorunlu, ancak DB'de opsiyonel tutulup uygulama katmanında kontrol edilir)
    facebook_url text,
    youtube_url text,
    twitch_tv_url text,
    instagram_url text,
    twitter_url text,
    blog_url text,
    other_social_media text,
    
    -- 3. Bütçe Beklentisi (Zorunlu Alan)
    budget_per_share numeric NOT NULL, -- Ücret tutarı (para birimi varsayılan olarak TRY)
    
    -- Yönetim Amaçlı Alanlar
    status text default 'new' NOT NULL, -- Başvuru durumu: 'new', 'reviewed', 'accepted', 'rejected'
    
    -- Primary Key Constraint
    CONSTRAINT influencer_applications_pkey PRIMARY KEY (id),
    
    -- E-posta tekrarını önlemek için unique constraint (opsiyonel - isterseniz kaldırabilirsiniz)
    CONSTRAINT unique_email UNIQUE (email)
);

-- 2. ROW LEVEL SECURITY (RLS) ETKİNLEŞTİRME
-- Tablonuzda RLS'nin etkin olduğundan emin olun
ALTER TABLE public.influencer_applications ENABLE ROW LEVEL SECURITY;

-- 3. RLS POLİTİKALARI
-- Yeni başvuru eklenmesine izin veren politika (Anonim kullanıcılar için)
-- Bu politika, giriş yapmamış kullanıcıların (anonim) form verilerini başarıyla göndermesini sağlar
CREATE POLICY "Anon users can submit applications."
ON public.influencer_applications 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Yöneticiler için tüm verileri görüntüleme politikası (Opsiyonel)
-- Eğer authenticated kullanıcılarınız varsa ve onların verileri görmesini istiyorsanız:
-- CREATE POLICY "Authenticated users can view applications."
-- ON public.influencer_applications 
-- FOR SELECT 
-- TO authenticated 
-- USING (true);

-- ============================================
-- MÜŞTERİ (MARKA) BAŞVURU TABLOSU
-- ============================================

-- 1. CUSTOMER APPLICATIONS TABLO OLUŞTURMA
-- customer_applications tablosunu oluşturur
CREATE TABLE IF NOT EXISTS public.customer_applications (
    -- Otomatik olarak artan ve birincil anahtar (Primary Key)
    id bigint generated by default as identity NOT NULL,
    
    -- Başvuru zaman damgası (Supabase otomatik olarak ekleyebilir)
    created_at timestamp with time zone default now() NOT NULL,
    
    -- 1. Kişisel ve Marka Bilgileri
    full_name text NOT NULL,
    brand text NOT NULL,
    tax_number text, -- Vergi numarası (isteğe bağlı)
    phone_number text NOT NULL,
    
    -- 2. Platform ve İçerik Seçimi
    platform text NOT NULL, -- 'instagram', 'youtube', 'tiktok'
    content_type text NOT NULL, -- Platforma göre: 'reels', 'story', 'pr', 'shorts', 'video'
    
    -- 3. Proje Detayları
    description text NOT NULL,
    
    -- Yönetim Amaçlı Alanlar
    status text default 'new' NOT NULL, -- Başvuru durumu: 'new', 'reviewed', 'accepted', 'rejected'
    
    -- Primary Key Constraint
    CONSTRAINT customer_applications_pkey PRIMARY KEY (id)
);

-- 2. ROW LEVEL SECURITY (RLS) ETKİNLEŞTİRME
-- Tablonuzda RLS'nin etkin olduğundan emin olun
ALTER TABLE public.customer_applications ENABLE ROW LEVEL SECURITY;

-- 3. RLS POLİTİKALARI
-- Yeni müşteri başvurusu eklenmesine izin veren politika (Anonim kullanıcılar için)
CREATE POLICY "Anon users can submit customer applications."
ON public.customer_applications 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Yöneticiler için tüm verileri görüntüleme politikası (Opsiyonel)
-- Eğer authenticated kullanıcılarınız varsa ve onların verileri görmesini istiyorsanız:
-- CREATE POLICY "Authenticated users can view customer applications."
-- ON public.customer_applications 
-- FOR SELECT 
-- TO authenticated 
-- USING (true);

-- ============================================
-- NOTLAR:
-- ============================================
-- 1. Bu SQL komutlarını Supabase Dashboard > SQL Editor'de çalıştırın
-- 2. RLS politikaları güvenlik için çok önemlidir - mutlaka ekleyin
-- 3. E-posta unique constraint'i istemiyorsanız, o satırı kaldırabilirsiniz
-- 4. Yönetici paneli için ayrı bir politika oluşturmanız gerekebilir
-- 5. Service Role Key kullanarak backend'den veri çekebilirsiniz (güvenli bir şekilde)
-- 6. Platform değerleri: 'instagram', 'youtube', 'tiktok'
-- 7. İçerik tipleri:
--    - Instagram: 'reels', 'story', 'pr'
--    - YouTube: 'shorts'
--    - TikTok: 'video'
-- ============================================
